name: Example CI/CD Github Action
on:
  pull_request:
    branches: [ uat ]
    types: [opened, synchronize, reopened, ready_for_review]
    paths:
      - 'applications/**'
jobs:
  validate:
    name: Validate
    runs-on: ubuntu-latest
    if: github.event.pull_request.draft == false
    steps:
      - name: Setup Node Environment
        uses: actions/setup-node@v2-beta
        with:
          node-version: '12'
      - name: Checkout Local Repo
        uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - name: Salesforce SFDX CLI Action
        uses: sfdx-actions/setup-sfdx@v1
        with:
          sfdx-auth-url: ${{ secrets.AUTH_SECRET }}
      - name: sfdx-test-run
        run: sfdx force:apex:test:run -l RunLocalTests -w 30